version: '3.8'

services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - monitor
    environment:
      - AUTH_API=http://auth:3001

  monitor:
    build:
      context: .
      dockerfile: apps/monitor/Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/monitor

volumes:
  mongo-data: